#   _____ __ _____ _____ __ __
#  |  |  |__|_   _|_   _|  |  |
#  |    -|  | | |   | | |_   _|
#  |__|__|__| |_|   |_|   |_|
#
#  by Bina


# -- font config --
font_family               JetBrainsMono Nerd Font
bold_font                 auto
italic_font               auto
bold_italic_font          auto
font_size                 13

# -- window --
window_margin_width       5 7
window_resize_step_cells  5
window_resize_step_lines  2
confirm_os_window_close   0

# -- misc settings --
enable_audio_bell         no
force_ltr                 no
detect_urls               yes
open_url_with             default
copy_on_select            yes

# -- color scheme --
background_opacity        0.9
background_blur           3

# Nord theme
foreground            #D8DEE9
background            #2A3440
selection_foreground  #d8dee9
selection_background  #4c566a
url_color             #81a1c1
cursor                #d8dee9

# black
color0   #3b4252
color8   #4C566A

# red
color1   #BF616A
color9   #BF616A

# green
color2   #A3BE8C
color10  #A3BE8C

# yellow
color3   #EBCB8B
color11  #EBCB8B

# blue
color4  #81A1C1
color12 #81A1C1

# magenta
color5   #B48EAD
color13  #B48EAD

# cyan
color6   #88C0D0
color14  #8FBCBB

# white
color7   #E5E9F0
color15  #eceff4
